[workspace]
resolver = "2"
members = ["app/src-tauri", "crates/core", "crates/gateway", "crates/adapters", "crates/cli"]

[workspace.package]
version = "0.1.9"
edition = "2021"
authors = ["john2ai <john@lightconsen.com>"]
license = "GPL-3.0-or-later"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
