import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
// Stamps the version and licence into the page's SOURCES (site/src/), not the
// built artifact — site/index.html is generated by scripts/build-site.mjs and
// carries whatever the sources had at build time. The site workflow chains
// sync-site → build-site before the upload, so the deployed page is current.
const TEMPLATE = join(ROOT, "site", "src", "index.html");
const I18N = join(ROOT, "site", "src", "i18n.ts");
const check = process.argv.includes("--check");

const pkg = JSON.parse(readFileSync(join(ROOT, "app", "package.json"), "utf8"));
const { version, license } = pkg;
if (!version || !license) {
  console.error("sync-site: package.json has no `version` or no `license`");
  process.exit(2);
}

// 1. The release line. Anchored on the platform list that follows it rather
//    than on `v<semver>` alone, so a version mentioned in prose elsewhere is
//    not caught by accident. Appears twice in the sources: the template's own
//    default text (what a reader without JS sees) and the zh dictionary entry
//    in i18n.ts — both must match, both get stamped.
const RELEASE_LINE = /v\d+\.\d+\.\d+(?= · <b>macOS 12\+<\/b>)/g;
// 2. The licence link's text, found by its target: the anchor that points at
//    the LICENSE file. Its text is the SPDX identifier, verbatim. Lives in the
//    template only (the footer is not translated).
const LICENSE_LINK = /(<a href="[^"]*\/LICENSE"[^>]*>)([^<]*)(<\/a>)/g;

const TARGETS = [
  { path: TEMPLATE, label: "template", transforms: ["release", "license"] },
  { path: I18N, label: "i18n.ts", transforms: ["release"] },
];

const edits = [];
for (const target of TARGETS) {
  const html = readFileSync(target.path, "utf8");
  let next = html;

  if (target.transforms.includes("release")) {
    const hits = [...next.matchAll(RELEASE_LINE)];
    if (hits.length === 0) {
      console.error(
        `sync-site: no release line matched in ${target.label} — it was reworded, so the\n` +
          "           anchor in this script no longer describes the page. Fix the\n" +
          "           pattern rather than deleting the check: silence here means the\n" +
          "           version silently stops being stamped.",
      );
      process.exit(2);
    }
    next = next.replace(RELEASE_LINE, `v${version}`);
    for (const hit of hits) {
      if (hit[0] !== `v${version}`) edits.push(`${target.label} release line: ${hit[0]} -> v${version}`);
    }
  }

  if (target.transforms.includes("license")) {
    const hits = [...next.matchAll(LICENSE_LINK)];
    if (hits.length === 0) {
      console.error(`sync-site: no link to the LICENSE file found in ${target.label}'s footer`);
      process.exit(2);
    }
    next = next.replace(LICENSE_LINK, (_, open, text, close) => {
      if (text !== license) edits.push(`${target.label} licence link: ${text} -> ${license}`);
      return `${open}${license}${close}`;
    });
  }

  if (next !== html) writeFileSync(target.path, next);
}

if (edits.length === 0) {
  console.log(`sync-site: already current (v${version}, ${license})`);
  process.exit(0);
}
if (check) {
  console.error(`sync-site: site/src is stale:\n  ${edits.join("\n  ")}`);
  process.exit(1);
}
console.log(`sync-site: ${edits.join("\n           ")}`);
