import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
// Stamps the version and licence into the page's SOURCES (site/src/), not the
// built artifact — site/index.html is generated by scripts/build-site.mjs and
// carries whatever the sources had at build time. The site workflow chains
// sync-site → build-site before the upload, so the deployed page is current.
const TEMPLATE = join(ROOT, "site", "src", "index.html");
const I18N_DIR = join(ROOT, "site", "src", "i18n");
const check = process.argv.includes("--check");

const pkg = JSON.parse(readFileSync(join(ROOT, "app", "package.json"), "utf8"));
const { version, license } = pkg;
if (!version || !license) {
  console.error("sync-site: package.json has no `version` or no `license`");
  process.exit(2);
}

// 1. The release line. Anchored on the platform list that follows it rather
//    than on `v<semver>` alone, so a version mentioned in prose elsewhere is
//    not caught by accident. It lives once per language: the template's own
//    default text (what a reader without JS sees) and one entry per dictionary
//    — every one of them gets stamped, which is why the dictionary list below
//    is read off the directory rather than named: a new language adds a file,
//    and a file nobody stamped would sit at the old version forever, quietly.
// The anchor is what follows the version, and it now has a word between the two
// that differs per language (`just released` / `正式发布` / `正式發布` /
// `リリース`), so the lookahead allows one such clause: anything that is not a
// separator or a line break, then the platform list. It matched the older
// `v0.2.9 · <b>macOS 12+` too — the clause is allowed to be empty — which is
// what makes the change backward compatible with a line nobody has reworded.
const RELEASE_LINE = /v\d+\.\d+\.\d+(?=[^·\n]* · <b>macOS 12\+<\/b>)/g;
// 2. The licence link's text, found by its target: the anchor that points at
//    the LICENSE file. Its text is the SPDX identifier, verbatim. Lives in the
//    template only (the footer is not translated).
const LICENSE_LINK = /(<a href="[^"]*\/LICENSE"[^>]*>)([^<]*)(<\/a>)/g;

// index.ts is the locale table, not a dictionary: it carries no copy of its own
// and so no release line, and asking it for one would trip the check below —
// which is how this list came to be written. Every other file in there is one
// language's overlay, and every one of them must be stamped.
const DICTIONARIES = readdirSync(I18N_DIR)
  .filter((f) => f.endsWith(".ts") && f !== "index.ts")
  .sort()
  .map((f) => ({ path: join(I18N_DIR, f), label: `i18n/${f}`, transforms: ["release"] }));

const TARGETS = [
  { path: TEMPLATE, label: "template", transforms: ["release", "license"] },
  ...DICTIONARIES,
];

const edits = [];
for (const target of TARGETS) {
  const html = readFileSync(target.path, "utf8");
  let next = html;

  if (target.transforms.includes("release")) {
    const hits = [...next.matchAll(RELEASE_LINE)];
    if (hits.length === 0) {
      console.error(
        `sync-site: no release line matched in ${target.label} — it was reworded, so the\n` +
          "           anchor in this script no longer describes the page. Fix the\n" +
          "           pattern rather than deleting the check: silence here means the\n" +
          "           version silently stops being stamped.",
      );
      process.exit(2);
    }
    next = next.replace(RELEASE_LINE, `v${version}`);
    for (const hit of hits) {
      if (hit[0] !== `v${version}`) edits.push(`${target.label} release line: ${hit[0]} -> v${version}`);
    }
  }

  if (target.transforms.includes("license")) {
    const hits = [...next.matchAll(LICENSE_LINK)];
    if (hits.length === 0) {
      console.error(`sync-site: no link to the LICENSE file found in ${target.label}'s footer`);
      process.exit(2);
    }
    next = next.replace(LICENSE_LINK, (_, open, text, close) => {
      if (text !== license) edits.push(`${target.label} licence link: ${text} -> ${license}`);
      return `${open}${license}${close}`;
    });
  }

  if (next !== html) writeFileSync(target.path, next);
}

if (edits.length === 0) {
  console.log(`sync-site: already current (v${version}, ${license})`);
  process.exit(0);
}
if (check) {
  console.error(`sync-site: site/src is stale:\n  ${edits.join("\n  ")}`);
  process.exit(1);
}
console.log(`sync-site: ${edits.join("\n           ")}`);
