// Icon metadata (display name + brand default color), trimmed from cc-switch
// (https://github.com/farion1231/cc-switch) to the fields Kiwano renders.

export interface IconMetadata {
  name: string;
  displayName: string;
  defaultColor: string;
}

export const iconMetadata: Record<string, IconMetadata> = {
  groq: { name: "groq", displayName: "Groq", defaultColor: "#F55036" },
  together: { name: "together", displayName: "Together AI", defaultColor: "#0F6FFF" },
  "9527code": { name: "9527code", displayName: "9527CODE", defaultColor: "currentColor" },
  "a6api": { name: "a6api", displayName: "A6API", defaultColor: "#3B82F6" },
  "aicodewith": { name: "aicodewith", displayName: "AICodeWith", defaultColor: "#3A3B40" },
  "aigocode": { name: "aigocode", displayName: "AIGoCode", defaultColor: "#5B7FFF" },
  "apikeyfun": { name: "apikeyfun", displayName: "APIKEY.FUN", defaultColor: "#9C3F00" },
  "apinebula": { name: "apinebula", displayName: "APINebula", defaultColor: "#C86F49" },
  "atlascloud": { name: "atlascloud", displayName: "AtlasCloud", defaultColor: "#111111"  },
  "sudocode": { name: "sudocode", displayName: "SudoCode.chat", defaultColor: "#111111"  },
  "sudocode-us": { name: "sudocode-us", displayName: "SudoCode.us", defaultColor: "#111111" },
  "alibaba": { name: "alibaba", displayName: "Alibaba", defaultColor: "#FF6A00" },
  "amux": { name: "amux", displayName: "Amux", defaultColor: "#000000" },
  "anthropic": { name: "anthropic", displayName: "Anthropic", defaultColor: "#D4915D" },
  "aws": { name: "aws", displayName: "AWS", defaultColor: "#FF9900" },
  "azure": { name: "azure", displayName: "Azure", defaultColor: "#0078D4" },
  "baidu": { name: "baidu", displayName: "Baidu", defaultColor: "#2932E1" },
  "bailian": { name: "bailian", displayName: "Bailian", defaultColor: "#624AFF" },
  "bytedance": { name: "bytedance", displayName: "bytedance", defaultColor: "currentColor" },
  "huoshan": { name: "huoshan", displayName: "Volcano Ark", defaultColor: "#3370FF" },
  "byteplus": { name: "byteplus", displayName: "BytePlus", defaultColor: "#3370FF" },
  "ccsub": { name: "ccsub", displayName: "CCSub", defaultColor: "#1E88E5" },
  "subrouter": { name: "subrouter", displayName: "SubRouter", defaultColor: "#0D9488" },
  "chatglm": { name: "chatglm", displayName: "chatglm", defaultColor: "currentColor" },
  "claude": { name: "claude", displayName: "Claude", defaultColor: "#D4915D" },
  "cherryin": { name: "cherryin", displayName: "CherryIN", defaultColor: "#FB6354" },
  "claudeapi": { name: "claudeapi", displayName: "ClaudeAPI", defaultColor: "#F38020" },
  "code0": { name: "code0", displayName: "Code0", defaultColor: "#20C050" },
  "cohere": { name: "cohere", displayName: "Cohere", defaultColor: "#39594D" },
  "copilot": { name: "copilot", displayName: "copilot", defaultColor: "currentColor" },
  "etok": { name: "etok", displayName: "ETok", defaultColor: "#F97316" },
  "fenno": { name: "fenno", displayName: "FennoAI", defaultColor: "#000000"  },
  "zetaapi": { name: "zetaapi", displayName: "ZetaAPI", defaultColor: "#000000"  },
  "teamorouter": { name: "teamorouter", displayName: "TeamoRouter", defaultColor: "#000000"  },
  "cubence": { name: "cubence", displayName: "Cubence", defaultColor: "#4B5563" },
  "deepseek": { name: "deepseek", displayName: "DeepSeek", defaultColor: "#1E88E5" },
  "doubao": { name: "doubao", displayName: "doubao", defaultColor: "currentColor" },
  "gemini": { name: "gemini", displayName: "Gemini", defaultColor: "#4285F4" },
  "gemma": { name: "gemma", displayName: "gemma", defaultColor: "currentColor" },
  "github": { name: "github", displayName: "GitHub", defaultColor: "#181717" },
  "githubcopilot": { name: "githubcopilot", displayName: "githubcopilot", defaultColor: "currentColor" },
  "google": { name: "google", displayName: "Google", defaultColor: "#4285F4" },
  "googlecloud": { name: "googlecloud", displayName: "googlecloud", defaultColor: "currentColor" },
  "grok": { name: "grok", displayName: "grok", defaultColor: "currentColor" },
  "huawei": { name: "huawei", displayName: "Huawei", defaultColor: "#FF0000" },
  "huggingface": { name: "huggingface", displayName: "Hugging Face", defaultColor: "#FFD21E" },
  "hunyuan": { name: "hunyuan", displayName: "hunyuan", defaultColor: "currentColor" },
  "kimi": { name: "kimi", displayName: "Kimi", defaultColor: "#1783FF" },
  "meta": { name: "meta", displayName: "Meta", defaultColor: "#0081FB" },
  "midjourney": { name: "midjourney", displayName: "midjourney", defaultColor: "currentColor" },
  "minimax": { name: "minimax", displayName: "MiniMax", defaultColor: "#FF6B6B" },
  "zenmux": { name: "zenmux", displayName: "ZenMux", defaultColor: "#6366F1" },
  "mistral": { name: "mistral", displayName: "Mistral", defaultColor: "#FF7000" },
  "nekocode": { name: "nekocode", displayName: "NekoCode", defaultColor: "#A64BC4" },
  "newapi": { name: "newapi", displayName: "newapi", defaultColor: "currentColor" },
  "notion": { name: "notion", displayName: "notion", defaultColor: "currentColor" },
  "ollama": { name: "ollama", displayName: "ollama", defaultColor: "currentColor"  },
  "openai": { name: "openai", displayName: "OpenAI", defaultColor: "currentColor" },
  "openclaw": { name: "openclaw", displayName: "OpenClaw", defaultColor: "#ff4f40" },
  "hermes": { name: "hermes", displayName: "Hermes", defaultColor: "#000000"  },
  "packycode": { name: "packycode", displayName: "PackyCode", defaultColor: "currentColor" },
  "pateway": { name: "pateway", displayName: "PatewayAI", defaultColor: "currentColor" },
  "perplexity": { name: "perplexity", displayName: "Perplexity", defaultColor: "#20808D" },
  "qwen": { name: "qwen", displayName: "qwen", defaultColor: "currentColor" },
  "stability": { name: "stability", displayName: "stability", defaultColor: "currentColor" },
  "tencent": { name: "tencent", displayName: "Tencent", defaultColor: "#00A4FF" },
  "unity2": { name: "unity2", displayName: "Unity2.ai", defaultColor: "#000000" },
  "vercel": { name: "vercel", displayName: "vercel", defaultColor: "currentColor" },
  "wenxin": { name: "wenxin", displayName: "wenxin", defaultColor: "currentColor" },
  "xai": { name: "xai", displayName: "xai", defaultColor: "currentColor"  },
  "yi": { name: "yi", displayName: "yi", defaultColor: "currentColor" },
  "zeroone": { name: "zeroone", displayName: "zeroone", defaultColor: "currentColor" },
  "zhipu": { name: "zhipu", displayName: "Zhipu AI", defaultColor: "#0F62FE" },
  "openrouter": { name: "openrouter", displayName: "OpenRouter", defaultColor: "#6566F1" },
  "pipellm": { name: "pipellm", displayName: "PIPELLM", defaultColor: "currentColor" },
  "qiniu": { name: "qiniu", displayName: "Qiniu Cloud", defaultColor: "#00AAE7" },
  "runapi": { name: "runapi", displayName: "RunAPI", defaultColor: "currentColor" },
  "shengsuanyun": { name: "shengsuanyun", displayName: "Shengsuanyun", defaultColor: "currentColor" },
  "lioncc": { name: "lioncc", displayName: "LionCC", defaultColor: "#F9DA3C" },
  "longcat": { name: "longcat", displayName: "LongCat", defaultColor: "#29E154" },
  "modelscope": { name: "modelscope", displayName: "ModelScope", defaultColor: "#624AFF" },
  "aihubmix": { name: "aihubmix", displayName: "AiHubMix", defaultColor: "#006FFB" },
  "xiaomimimo": { name: "xiaomimimo", displayName: "Xiaomi MiMo", defaultColor: "#000000" },
  sssaicode: { name: "sssaicode", displayName: "SSSAiCode", defaultColor: "#08080e" },
  "novita": { name: "novita", displayName: "Novita AI", defaultColor: "#000000"  },
  "nvidia": { name: "nvidia", displayName: "NVIDIA", defaultColor: "#74B71B" },
  "stepfun": { name: "stepfun", displayName: "StepFun", defaultColor: "#005AFF" },
  "ppio": { name: "ppio", displayName: "PPIO", defaultColor: "#2874FF" },
  "jiekou": { name: "jiekou", displayName: "JieKou AI", defaultColor: "#000000"  },
  "xycai": { name: "xycai", displayName: "XycAi", defaultColor: "#1E88E5" },
};

export function getIconMetadata(name: string): IconMetadata | undefined {
  return iconMetadata[name.toLowerCase()];
}
